### ISSUE TITLE
Expose the 'encryptForm' function

### ISSUE THREAD

**Issue by justqyx** [Worldpay/worldpay-cse-lib-javascript#2]
I recommond to expose the `encryptForm` function, so we can decide the moment to encrypt the credit card information and fill it into the relative `hidden input`.

 For example, in global business, the customer have to fill the his/her card number first and then we can decide which Payment Gateway(Worldpay,Braintree,Cybersource) to use. After the customer fill all of the credit card information we invoke the choosen Payment Gateway flow.

Therefore, it would be a better design if the `encryptForm` function will be exposed too.

**Comment by benwwest** [comment]
Hi, 

Thanks for the feedback.

We actually already offer the ability to simply encrypt the data without auto-submitting the form. 

If you take a look at the documentation [here](http://support.worldpay.com/support/kb/gg/client-side-encryption/Content/D%20-%20Integration/Custom%20Integration.htm) you will see there is an option to use the encrypt() function. You simply pass it the field values and it will return the encrypted string.

Its worth noting that this encryption will use a Worldpay public key to encrypt the data so the data can therefore only be decrypted by Worldpay.

**Comment by justqyx** [comment]
Hi @benwwest , thanks for your reply, I'll try the `encrypt()` way and I think it will work.
